[package]
name = "leptos-twelements"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.4", optional = true }
# console_error_panic_hook = "0.1"
# console_log = "1"
# cfg-if = "1"
leptos = { version = "0.4", features = ["nightly"] }
serde = "^1.0.188"
# leptos_axum = { version = "0.4", optional = true }
leptos_meta = { version = "0.4", features = ["nightly"] }
# leptos_router = { version = "0.4", features = ["nightly"] }
# log = "0.4"
# simple_logger = "4"
# tokio = { version = "1.25.0", optional = true }
# tower = { version = "0.4.13", optional = true }
# tower-http = { version = "0.4", features = ["fs"], optional = true }
# wasm-bindgen = "=0.2.87"
# thiserror = "1.0.38"
# tracing = { version = "0.1.37", optional = true }
# http = "0.2.8"

[features]
default = []
ssr = ["axum"]
axum = ["dep:axum"]
